Add login form

diff --git a/hooks/commit-msg b/hooks/commit-msg
--- a/hooks/commit-msg
+++ b/hooks/commit-msg
@@ -1,21 +1,21 @@
 #!/usr/bin/env bash
 
 if [ -z "$1" ]; then
-	echo "Missing argument (commit message). Did you try to run this manually?"
-	exit 1
+    echo "Missing argument (commit message). Did you try to run this manually?"
+    exit 1
 fi
 
 commitTitle="$(cat $1 | head -n1)"
 
 # ignore merge requests
 if echo "$commitTitle" | grep -qE "^Merge branch \'"; then
-	echo "Commit hook: ignoring branch merge"
-	exit 0
+    echo "Commit hook: ignoring branch merge"
+    exit 0
 fi
 
 # check semantic versioning scheme
-if ! echo "$commitTitle" | grep -qE '^(?:feat|fix|docs|style|refactor|perf|test|chore)\(?(?:\w+|\s|\-|_)?\)?:\s\w+'; then
-	echo "Your commit title did not follow semantic versioning: $commitTitle"
-	echo "Please see https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commit-message-format"
-	exit 1
+if ! echo "$commitTitle" | grep -qE '^(?:feat|fix|docs|style|refactor|perf|test|chore): \w+$'; then
+    echo "Your commit title did not follow semantic versioning: '$commitTitle'"
+    echo "Please see https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716"
+    exit 1
 fi
